name = "my-app"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

[vars]

DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNjBlODJkOTAtMDk3Mi00ZTYwLWIwNDUtN2QyNGE3ZmRjMjRkIiwidGVuYW50X2lkIjoiZTkyZGVlYWE4YjI4YjJjOTk4MGY5ODY1MjU1NGI3OGYwNWU4OTBkMGZlY2U1NGY2ZWIyYWRiZWQwZGQ2ODY1MCIsImludGVybmFsX3NlY3JldCI6ImQ2NjkwYTIyLWQwMmQtNGNiYS05M2UwLTljZmI4ODAwN2NlNSJ9.1QB2HDm9wv4XGl8EzIkcev0IN_dtHJkoeFZlyG1dh7I"
JWT_SECRET = "amal1secret"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"